### ISSUE TITLE
Proper "wordpress-muplugin" Composer package

### ISSUE THREAD

**Issue by szepeviktor** [joshcanhelp/wp-rest-api-auth0#1]
Please consider making it a proper `"type": "wordpress-muplugin"` package.
https://github.com/composer/installers#readme
Like so #2

And - maybe - provide a shim for those not managing their WordPress installation [with Composer](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress.md#semisecret-subdirectory-structure).
I know the ratio of Composer installs vs, plain installs is about 1:1000000.

**Comment by joshcanhelp** [comment]
Thanks for the tip here! I haven't even really released this yet ... how did you come across it?

**Comment by joshcanhelp** [comment]
@szepeviktor - What kind of shim would be helpful? This isn't really meant to be installed with Composer (hence the manual install instructions) but I'm  happy to make it work better in that case.

**Comment by szepeviktor** [comment]
I run a robot army 🤖🤖🤖🤖🤖 and you are being monitored :)
