### ISSUE TITLE
M2M Authentication Issues with WP REST API Auth0 Plugin

### ISSUE THREAD

**Issue by ludovicsclain** [joshcanhelp/wp-rest-api-auth0#12]
**Description**:

I am trying to integrate Auth0 with my WordPress site to secure access to the REST API. I followed the procedure described in [this article](https://www.joshcanhelp.com/protect-wordpress-rest-api-with-oauth2-auth0/) and used the [WP REST API Auth0](https://github.com/joshcanhelp/wp-rest-api-auth0) plugin.

To provide context, the goal is to make REST API requests from automation services like Pabbly Connect or Zapier. For my tests, I used Postman.

Here's a summary of the steps I've taken and the issues I've encountered:

1. **Installation and Configuration**:
   - I installed the [Auth0 for WordPress](https://wordpress.org/plugins/auth0/) plugin.
   - I also installed the [WP REST API Auth0](https://github.com/joshcanhelp/wp-rest-api-auth0) plugin from the admin dashboard.
   - I configured my applications and permissions from the Auth0 dashboard.

2. **Obtaining the Bearer Token**:
   - I attempted to obtain a Bearer Token using the following request:
```
{
    "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "client_secret": "xxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "audience": "https://xx-xx.xxxxx.xx/wp-json/",
    "grant_type": "client_credentials"
}
```
   - Decoding the obtained Bearer Token, I get:
```
{
  "iss": "https://xxx-xxxxxxxxxxxxxxxx.xx.auth0.com/",
  "sub": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@clients",
  "aud": "https://xx-xx.xxxxx.xx/wp-json/",
  "iat": xxxxxxxxxx,
  "exp": xxxxxxxxxx,
  "azp": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "gty": "client-credentials"
}
```

3. **Logs and Errors**:
   - My WordPress site logs show the error: "Looking for Auth0 user ID... Could not find a user matching this the sub claim."
   - Decoding the Bearer Token reveals that the `sub` is based on the `client_id` and doesn't match any real user on my WordPress.

4. **Questions and Concerns**:
   - How can I correctly associate a WordPress user with an Auth0 token?
   - Are there additional steps or configurations that I might have missed to enable authentication via Auth0 for the WordPress REST API?

I would appreciate any help or guidance in resolving these issues. Thank you in advance.

**Comment by joshcanhelp** [comment]
Apologies for the delay in getting back to you here. This system allows for user-scoped access tokens, not machine to machine interactions like the one you're describing. Supporting that might be tough because WordPress relies on email addresses to associate actions to users. You're using a client credentials grant to generate the access token for another application, which is an absolutely valid way to generate an access token, but, as you can see in the token itself, the `sub` claim indicates an application, not a person (as expected). So the WordPress plugin can validate the token just fine but when it looks up that `sub` claim, it does not find a user associated.

This would be a solid addition to the plugin I created. Let me see if I can figure out a way to add that. I'm a little overloaded right now so no promises but I'll at least take a look and spec out a path forward in case you or someone else might be able to contribute that functionality.

**Comment by ludovicsclain** [comment]
> Apologies for the delay in getting back to you here. This system allows for user-scoped access tokens, not machine to machine interactions like the one you're describing. Supporting that might be tough because WordPress relies on email addresses to associate actions to users. You're using a client credentials grant to generate the access token for another application, which is an absolutely valid way to generate an access token, but, as you can see in the token itself, the `sub` claim indicates an application, not a person (as expected). So the WordPress plugin can validate the token just fine but when it looks up that `sub` claim, it does not find a user associated.
> 
> This would be a solid addition to the plugin I created. Let me see if I can figure out a way to add that. I'm a little overloaded right now so no promises but I'll at least take a look and spec out a path forward in case you or someone else might be able to contribute that functionality.

Hey Josh, thank you for your kind response (even if it was a bit late). I eventually managed to find a solution, and I even made a detailed tutorial to help others who might want to achieve the same. It's in French, but you can turn on the subtitles. I hope this will help the community 👉 https://www.youtube.com/watch?v=tFQcfebe9AM

**Comment by joshcanhelp** [comment]
@ludovicsclain - Thanks so much for sharing! I didn't get through the whole thing but I had some time to take a look at this and the `main` branch here now has a solution. Specifically this commit, if you want to try it out locally:

https://github.com/joshcanhelp/wp-rest-api-auth0/commit/f067f06d783394fdda4507ece89ab5fcd100a446

Basically, this lets you create a new user in WordPress, set a client ID as their username, and the plugin will accept M2M tokens for them. I'm working on updating the blog post with instructions for this and getting the new version out in Composer.

**Comment by joshcanhelp** [comment]
Fixed in https://github.com/joshcanhelp/wp-rest-api-auth0/releases/tag/v4.0.0

**Comment by ludovicsclain** [comment]
> I'm working on updating the blog post with instructions for this

Hey Josh 👋 Thank you so much for taking the time to make this possible. If I understood correctly, this means that with this version 4, my entire procedure on the Auth0 dashboard side remains the same, but that on the plugin side I would no longer have to go to the ~/wp-content/plugins folder /wp-rest-api-auth0-main/src and comment lines 108 to 118 of the file "wp-rest-api-auth0.php"?
![f1fd390a-4912-44f0-9f14-d16389407726](https://github.com/joshcanhelp/wp-rest-api-auth0/assets/13393845/284fbf2a-ea81-4bcd-a075-97b685c36353)

**Comment by joshcanhelp** [comment]
@ludovicsclain - I'm sorry I never responded. You will need to create a new user in WordPress with the Client ID of the application that's making the call as the user name. This, in effect, registers the calling application (the one getting the access token) so it can then be authorized to make changes to the site. Make sure to set an appropriate role for the calling application, only as high as the permissions it needs.

I truly do intend to write this up in a post soon!
