### ISSUE TITLE
"upload through the admin interface" will not work

### ISSUE THREAD

**Issue by szepeviktor** [joshcanhelp/wp-rest-api-auth0#6]
🚨 The admin interface can only be used to upload normal plugins.

Installing MU plugins needs file-level access (SFTP, SCP etc.) and some expertise.

**Comment by szepeviktor** [comment]
Please consider releasing it as normal plugin, putting libraries under a custom namespace with mozart.

**Comment by szepeviktor** [comment]
I leave the whole thing up to You.

**Comment by joshcanhelp** [comment]
It won't install it _as_ an MU plugin but you can download the ZIP here and install it in wp-admin
