### ISSUE TITLE
The meta key is incorrect with a non-default database table prefix

### ISSUE THREAD

**Issue by pmkemper** [joshcanhelp/wp-rest-api-auth0#9]
The plugin has the meta key wp_auth0_id hard coded, but when the database table prefix is anything but "wp_", this will fail.

This can be resolved by using:
```
global $wpdb;
$meta_key = $wpdb->prefix . 'auth0_id'
```

**Comment by joshcanhelp** [comment]
Thanks for the report @pmkemper! Rookie mistake on my part. Will get this fixed when I can.

**Comment by joshcanhelp** [comment]
Sorry for the delay ... releasing this fix now and thanks again for reporting!
